#docker-compose.yml
version: "3.5"

services:

  app:
    build: .
    container_name: bot_service_appointment
    volumes: ['./logs/:/app/logs/']
    command: ["python", "main.py"]
    networks:
      - proxynet

networks:
  proxynet:
    name: app_fastapi_postgres_app_fastapi_network
    external: true
